### ISSUE TITLE
#### Database connector

### ISSUE THREAD

**Issue by crnopster** [lvl484/positioning-filter#10]
Package storage has to provide an interface to create a new postgres client with ability to reconnect after connection failure.

Definition of done:

A database connection can be created and used for executing queries.
If database connection is lost and afterr it can be reestablished, client has to perform reconnection automatically.

**Comment by VasylKosiv** [comment]
And How you implement this issue: If database connection is lost and afterr it can be reestablished, client has to perform reconnection automatically
